### ISSUE TITLE
Missing SDL2 libraries on Linux.

### ISSUE THREAD

**Issue by ghost** [Capy64/Capy64#7]
**Side**
- [ ] Lua side
- [x] C# side
- [ ] Other
- [ ] I don't know

**Describe the bug**
Resizing the window completely freezes Capy64.

**To Reproduce**
1. Use linux.
2. Resize the window.

**Expected behavior**
I expected the window resize.

**Desktop (please complete the following information):**
 - OS: Fedora 37 x86_64
 - Version: 0.0.9-alpha

**Additional context**
[capylog.txt](https://github.com/Ale32bit/Capy64/files/10794470/capylog.txt)

**Comment by ghost** [comment]
also yes i have no idea how the check mark works

**Comment by Ale32bit** [comment]
The program is looking for SDL2 libraries in the local folder, but fails because they're not packaged during publish.

**Comment by ghost** [comment]
Changing [this](https://github.com/Ale32bit/Capy64/blob/main/Capy64/Extensions/Bindings/SDL2.cs#L23) line to this seems to fix the issue.
```cs
private const string SDL = "SDL2-2.0.so.0";
```

**Comment by Ale32bit** [comment]
Fixed in fd8b38932b3b8d333177bb4558e93cd95cffc3b6
