### ISSUE TITLE
Capy64 fails to properly initialize on Linux

### ISSUE THREAD

**Issue by autione** [Capy64/Capy64#8]
**Side**
- [ ] Lua side
- [X] C# side
- [ ] Other
- [ ] I don't know

**Describe the bug**
Screen doesn't really render anything, apart from the "Installing CapyOS..." text on first launch, and if resized, blacks out.
Console displays messages informing that it can't locate SDL2 files (libSDL2.dll.so, SDL2.dll, etc.) and errors.

**To Reproduce**
1. Simply launch Capy64 (preferably with a terminal, to see output)
2. See errors

**Expected behavior**
Capy64 to launch normally.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Fedora Linux 36, x86_64
 - Browser: Ungoogled Chromium
 - Version: (of Capy64) Alpha 0.0.9

**Additional context**
I included the console logs [here](https://github.com/Ale32bit/Capy64/files/10794531/log-uwu-mlem.txt). My guess is just that it's looking for the libraries at the wrong places, but I'm unsure.

**Comment by Ale32bit** [comment]
Related to #7
